### ISSUE TITLE
[RFE] Stopped Domain - Server/Server Group Power operations do not fail with notification

### ISSUE THREAD

**Issue by hhovsepy** [ManageIQ/manageiq-providers-hawkular#46]
When executing any Power operation on "Server" or 'Server Group" of Stopped EAP7 Domain, UI shows successful green notification that operation is scheduled successfully.
But no Power operation can be executed, as Domain Controller is Stopped, and in fact it is not executed.

Fix:
Show failure notification message that "Domain is Stopped" and no Power operation could be executed on Domain's Server Groups or Servers.

**Comment by hhovsepy** [comment]
Version master.20170911012949_

**Comment by abonas** [comment]
@josejulio please have a look.
@miq-bot add_label bug

**Comment by josejulio** [comment]
I'm not sure how we should handle this.
The operation is scheduled on the agent, and he will eventually answer with a failure.
We could check the domain availability state (after #44) and decide if we want to show the buttons or not, but the server could be up/down and we aren't sure because the data isn't "live" (the value is from the last refresh).

Currently, even standalone servers do this: (Server state is down, but operation is executed)
![screenshot from 2017-09-20 19-00-24](https://user-images.githubusercontent.com/3845764/30673134-9881aadc-9e36-11e7-90e1-a28fb1cfc198.png)

I suppose we should send a notification/event/not sure the correct term but basically, display something to the user when the operation is actually executed and we know for sure the operation outcome.

**Comment by abonas** [comment]
@josejulio thank you for the investigation
@jdoyleoss how would you like to handle this? would you like the buttons to be disabled/enabled based on last state known to miq even if it's an incorrect state in reality, or not?

**Comment by jdoyleoss** [comment]
I agree that we should check the domain availability state. I think we will have to live with the requirement to refresh, that's a limitation of MiQ, no?

I've heard targeted refresh frequently mentioned with the RHEV provider. Is that a solution to this issue?

I agree we should also notify on the operation outcome.

**Comment by abonas** [comment]
@jdoyleoss targeted refresh could improve the situation, it is still does not guarantee real time live accurate information on miq side. It would be good to have it but it is a big feature to work on.

**Comment by abonas** [comment]
so @jdoyleoss for now, without target refresh, how would you like to handle this? would you like the buttons to be disabled/enabled based on last state known to miq even if it's an incorrect state in reality, or not?

**Comment by jdoyleoss** [comment]
@abonas Yes.

**Comment by abonas** [comment]
@josejulio please see the answer above :)

**Comment by josejulio** [comment]
Great, Will do that!

**Comment by theute** [comment]
@josejulio what's the status on this ?

**Comment by josejulio** [comment]
I haven't done this, the task is now to enable/disable buttons depending on availability. 
This should also apply to every operation that is dependent of a server (standalone/domain).

**Comment by abonas** [comment]
@tumido please have a look at this, you can see the investigation above. please check how complicated/amount of work this is. thanks!

**Comment by abonas** [comment]
@hhovsepy is the RFE filed in bugzilla? if not, please close here and move it there (with link here for prior discussions, of course)

**Comment by hhovsepy** [comment]
BZ for this https://bugzilla.redhat.com/show_bug.cgi?id=1497922, so closing issue in github.
