### ISSUE TITLE
Create REST Api for POST on Middleware Server Operations

### ISSUE THREAD

**Issue by mtho11** [ManageIQ/manageiq-providers-hawkular#85]
For the angular dialog server operations such as:

- Add Datasource

- Add JDBC Driver

- Add Deployment

We now need the POST operations (the Read-only operations were just done) so we can move off of  ruby controller and migrate to angular/REST API.

**Comment by abonas** [comment]
@aljesusg please sync first with @cfcosta on this task as he recently added REST api.
Prioirity/urgency - this is NOT for the upcoming release, which means the UI will NOT be converted for the upcoming release to use it once it's added. But certainly is needed for the future.

**Comment by abonas** [comment]
removing the refactoring label. the REST api does not exist and as such it is enhancement and not refactoring. the refactoring label should be put on the UI PRs once they will be using the api.

**Comment by aljesusg** [comment]
Link to API PR added by @cfcosta https://github.com/ManageIQ/manageiq-api/pull/19

**Comment by aljesusg** [comment]
Hi working in this PR and checking the operations in https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/middleware_server_controller.rb the point is make this kinds of operations through the API CRUD that caina did in angular. isn't it? For example worki for add datasource in https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/assets/javascripts/controllers/middleware_datasource/middleware_datasource_controller.js file to go to the API instead the ruby controller.  I'm a little confused about because i understand in the call that I had with caina about change the controller to call the API endpoints instead that functions that make the operations in the engine.

**Comment by abonas** [comment]
@mtho11 please see @aljesusg questions above ^^

**Comment by mtho11** [comment]
@aljesusg yes, go to the API instead of the ruby controller. That is the main idea, Caina did it for Read operations but not the POST. For example `Add Datasource` needs an API so it can POST to API and not ruby controller - https://github.com/mtho11/manageiq-ui-classic/blob/80f5757bbb3c22bf84f9bd31af95f0c32332f889/app/assets/javascripts/controllers/middleware_datasource/middleware_datasource_service.js#L220

**Comment by aljesusg** [comment]
Ok @mtho11, @abonas  Thanks

**Comment by mtho11** [comment]
@aljesusg the bigger picture here is to remove all REST from any ruby controllers or route/resource in favor of a standalone API that can be: monitored, built-in security and scaled independently of UI. Eventually, all the ruby controllers in ui-classic will be migrated to an Angular SPA talking directly to REST API (and ui-classic will disappear). Eventually ;)
